# Generated by Django 5.2.14 on 2026-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_verified_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
