# Generated by Django 5.2.14 on 2026-05-31 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("room", "Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("rent", models.PositiveIntegerField()),
                ("deposit", models.PositiveIntegerField(default=0)),
                ("facilities", models.JSONField(blank=True, default=list)),
                ("rules", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "ownership_proof",
                    models.FileField(blank=True, upload_to="ownership_proofs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checklist", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="verification_photos/"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("need_evidence", "Need More Evidence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_reports",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
