# Generated by Django 5.2.14 on 2026-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
