# Generated by Django 5.2.14 on 2026-06-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("onboarding_submitted", "Onboarding Submitted"),
                    ("property_listed", "Property Listed"),
                    ("verification_visit_scheduled", "Verification Visit Scheduled"),
                    ("verification_visit_confirmed", "Verification Visit Confirmed"),
                    ("property_status_changed", "Property Status Changed"),
                ],
                max_length=80,
            ),
        ),
    ]
